# pybricks blocks file:{"blocks":{"languageVersion":0,"blocks":[{"type":"blockGlobalSetup","id":"bjK,wS1MYO7aiYkFSwd{","x":0,"y":0,"deletable":false,"next":{"block":{"type":"variables_setup_any","id":"ULP=k.[fy}tr9neVMn,F","fields":{"VAR":{"id":"}2_lreUOZt2@v?WL#y%k"}},"inputs":{"VALUE0":{"shadow":{"type":"blockMathNumber","id":"J4%R1P,Q0|QLw5m32DlN","fields":{"NUM":0}}}}}}},{"type":"blockGlobalStart","id":"3tJe|AWl0baN(wH9a$@.","x":0,"y":142,"deletable":false,"next":{"block":{"type":"blockFlowWhile","id":"$na|[fq@TXHk,sf4aAk5","fields":{"MODE":"WHILE"},"inputs":{"BOOL":{"shadow":{"type":"blockLogicTrue","id":"C|m@rtAAdM9G8wje^0*L"}},"DO":{"block":{"type":"blockVariableSetValue","id":";Y)+~_tPtu5Pq+.Gw2-T","inputs":{"VAR":{"shadow":{"type":"variables_get_any","id":"Ky~:p(dF|7Kx([vw-w]r","fields":{"VAR":{"id":"}2_lreUOZt2@v?WL#y%k","name":"key","type":"Any"}}}},"VALUE0":{"shadow":{"type":"blockMathNumber","id":"{AJa8tR?l#@!zz4(D@+b","fields":{"NUM":0}},"block":{"type":"blockReadInput","id":"tM,x2IVe$c_CA3$CNBz7","fields":{"METHOD":"READ_INPUT_LAST_CHAR"}}}},"next":{"block":{"type":"blockIfElse","id":"5-cQj),E,A78/Sdo~Jle","extraState":{"optionLevel":0},"inputs":{"IF0":{"shadow":{"type":"blockLogicTrue","id":"*G$cJEZ5.jZsqR)m~kHA"},"block":{"type":"blockVariableGetValue","id":"9GGbit8in~Q+89P0u[C,","inputs":{"VAR":{"shadow":{"type":"variables_get_any","id":"llPE6{myELpY7v|sAu63","fields":{"VAR":{"id":"}2_lreUOZt2@v?WL#y%k","name":"key","type":"Any"}}}}}}},"DO0":{"block":{"type":"blockPrint","id":"x)b^t%txBB]//.6o1Jo@","extraState":{"optionLevel":1},"fields":{"SEP":"SEP_SPACE"},"inputs":{"TEXT0":{"shadow":{"type":"text","id":"(/)l(#d:de}$!!]i=6E4","fields":{"TEXT":"You pressed:"}}},"TEXT1":{"shadow":{"type":"text","id":"Q7~cqAE$p6E{S{_R?wJl","fields":{"TEXT":"abc"}},"block":{"type":"blockVariableGetValue","id":"$j/C%1aK%oEQIcskq]aB","inputs":{"VAR":{"shadow":{"type":"variables_get_any","id":"25tXFQWJ4M^Ry5JrlWFP","fields":{"VAR":{"id":"}2_lreUOZt2@v?WL#y%k","name":"key","type":"Any"}}}}}}}}}}}}}}}}}}}]},"variables":[{"name":"red","id":"#y(x%Jp.F7Z]+G9WDI0%","type":"ColorDef"},{"name":"orange","id":"-0jaDtSA%iAKPFqR|n.Z","type":"ColorDef"},{"name":"yellow","id":"18O~w,)%$=!._{}GL`gO","type":"ColorDef"},{"name":"green","id":"!(8#oe%v|=`f3[Me6N-#","type":"ColorDef"},{"name":"cyan","id":"=-/k*3v!Wb6L{l-0-!C5","type":"ColorDef"},{"name":"blue","id":":3*/(0G45BfP(73).sjk","type":"ColorDef"},{"name":"violet","id":"EB=cLJ|h23,a,+Ot)Le4","type":"ColorDef"},{"name":"magenta","id":"V`ARTtv3NfQ@^40h^_F9","type":"ColorDef"},{"name":"white","id":"QoAXsG27wCS8/!^UaBjp","type":"ColorDef"},{"name":"none","id":"VlUUUw=qChp3*tkBq3/n","type":"ColorDef"},{"name":"key","id":"}2_lreUOZt2@v?WL#y%k","type":"Any"}],"info":{"type":"pybricks","version":"1.2.2"}}
from pybricks.tools import read_input_byte

# Initialize variables.
key = 0


# The main program starts here.
while True:
    key = read_input_byte(True, True)
    if key:
        print('You pressed:', key)
