# pybricks blocks file:{"blocks":{"languageVersion":0,"blocks":[{"type":"blockGlobalSetup","id":"bjK,wS1MYO7aiYkFSwd{","x":67,"y":76,"deletable":false,"next":{"block":{"type":"variables_set_motor","id":"Li0GS#JlmwlX?qqo.i-%","fields":{"VAR":{"id":"opIxK950#Kqx++BZ%U}%"}},"inputs":{"PORT":{"shadow":{"type":"blockParametersPort","id":"0qW/A]=~w#,^g]*^nH4g","fields":{"NAME":"A"}}},"POSITIVE_DIRECTION":{"shadow":{"type":"blockParametersDirection","id":"!X)CqPiE4ur(F!/YI8e*","fields":{"SELECTION":"Direction.CLOCKWISE"}}}}}}},{"type":"blockGlobalStart","id":"3tJe|AWl0baN(wH9a$@.","x":68,"y":233,"deletable":false,"next":{"block":{"type":"blockFlowRepeat","id":"ioJF;:WYvo(Z.(;[h*M3","inputs":{"TIMES":{"shadow":{"type":"blockMathNumber","id":"z[GFF.]C2Vv54)3]6!+B","fields":{"NUM":8}}},"DO":{"block":{"type":"blockPrint","id":"j,,T}?rBkaW$1v?olp4p","extraState":{"optionLevel":0},"inputs":{"TEXT0":{"shadow":{"type":"text","id":"!x5.0YiWya^`(y)yO5B8","fields":{"TEXT":"Hello, World!"}}}},"next":{"block":{"type":"blockMotorRun","id":"XN7bivu)1*{0H]EB!D^/","extraState":{"optionLevel":1},"fields":{"METHOD":"MOTOR_RUN_FOR"},"inputs":{"VAR":{"shadow":{"type":"variables_get_motor_device","id":"iG*/d9OccHt+#y2z_2HU","fields":{"VAR":{"id":"opIxK950#Kqx++BZ%U}%","name":"motor","type":"Motor"}}}},"VALUE0":{"shadow":{"type":"unit_angularVelocity","id":"`Y9^|gA:[Df]y$K6x7B6","fields":{"VALUE0":500}}},"ANGLE":{"shadow":{"type":"unit_angle","id":"=pOPL*u+DA@e%`GK+(uy","fields":{"VALUE0":90}}},"THEN":{"shadow":{"type":"parameters_stop_4","id":"r]sNWLj5!FTVL5%UsC=s","fields":{"VALUE":"Stop.HOLD"}}}}}}}}}}}}]},"variables":[{"name":"red","id":"Rd/OJ1i9A.n}r^mxrwiC","type":"ColorDef"},{"name":"orange","id":"=;H36S2U6`0i*2MS[A-I","type":"ColorDef"},{"name":"yellow","id":"!KX.F,3E,LM0)HIk~55i","type":"ColorDef"},{"name":"green","id":"c*XK$sXeoIJiZ(~Vv0g(","type":"ColorDef"},{"name":"cyan","id":"Dv6+GDE5A~JK=/|WNH+6","type":"ColorDef"},{"name":"blue","id":"BUb9D~b9@DCMj)5ABtPv","type":"ColorDef"},{"name":"violet","id":"pbETHA7L8rhz|VUz/PoF","type":"ColorDef"},{"name":"magenta","id":"EyYra%JBD3Gc|d.8oiqn","type":"ColorDef"},{"name":"white","id":"z(ys*w)`T0)Y`mqJIcGX","type":"ColorDef"},{"name":"none","id":"%#y6qX^b$=8CiD*esT)u","type":"ColorDef"},{"name":"motor","id":"opIxK950#Kqx++BZ%U}%","type":"Motor"}],"info":{"type":"pybricks","version":"1.2.3"}}
from pybricks.parameters import Direction, Port, Stop
from pybricks.pupdevices import Motor

# Set up all devices.
motor = Motor(Port.A, Direction.CLOCKWISE)


# The main program starts here.
for count in range(8):
    print('Hello, World!')
    motor.run_angle(500, 90)
