# pybricks blocks file:{"blocks":{"languageVersion":0,"blocks":[{"type":"blockGlobalSetup","id":"bjK,wS1MYO7aiYkFSwd{","x":0,"y":0,"deletable":false,"next":{"block":{"type":"variables_set_motor","id":"0.rn^SUnYNwT*p+~A]wF","fields":{"VAR":{"id":"oa=6ALE#Lhs`C.PoT*$y"}},"inputs":{"PORT":{"shadow":{"type":"blockParametersPort","id":"`C[=k58L6Wlc)k@Gz*IW","fields":{"NAME":"A"}}},"POSITIVE_DIRECTION":{"shadow":{"type":"blockParametersDirection","id":"nY_t}pX/WFt_9Jf-^--0","fields":{"SELECTION":"Direction.CLOCKWISE"}}}}}}},{"type":"blockGlobalStart","id":"3tJe|AWl0baN(wH9a$@.","x":0,"y":148,"deletable":false,"next":{"block":{"type":"blockMotorRun","id":"1dD*-Z16c1yHi55c_IKj","extraState":{"optionLevel":1},"fields":{"METHOD":"MOTOR_RUN_FOR"},"inputs":{"VAR":{"shadow":{"type":"variables_get_motor_device","id":"E;pAD3fSAr/-3tq[H+;x","fields":{"VAR":{"id":"oa=6ALE#Lhs`C.PoT*$y","name":"motor","type":"Motor"}}}},"VALUE0":{"shadow":{"type":"unit_angularVelocity","id":"ccuKCb+O5lKXN{e7Ej.o","fields":{"VALUE0":500}}},"ANGLE":{"shadow":{"type":"unit_angle","id":"3Pl9}%pRU+01GA~fOva$","fields":{"VALUE0":360}}},"THEN":{"shadow":{"type":"parameters_stop_4","id":"b*.]iPinfLjJ.qW50o+9","fields":{"VALUE":"Stop.HOLD"}}}},"next":{"block":{"type":"blockWaitTime","id":"~!Rfuy}irsbd8?H}o]St","inputs":{"VALUE0":{"shadow":{"type":"unit_time","id":"b}(px:I^G+15sa;$fc,`","fields":{"VALUE0":1000}}}},"next":{"block":{"type":"blockMotorRun","id":"b$8Itju.H]+)[Vt/.R!g","extraState":{"optionLevel":1},"fields":{"METHOD":"MOTOR_RUN_FOR"},"inputs":{"VAR":{"shadow":{"type":"variables_get_motor_device","id":"YHLyVXG9xb8voqaNim_g","fields":{"VAR":{"id":"oa=6ALE#Lhs`C.PoT*$y","name":"motor","type":"Motor"}}}},"VALUE0":{"shadow":{"type":"unit_angularVelocity","id":"mPWWf`p%b+%iFbb~MT!N","fields":{"VALUE0":500}}},"ANGLE":{"shadow":{"type":"unit_angle","id":"=9^YReD-p*?*%1/S6bML","fields":{"VALUE0":-360}}},"THEN":{"shadow":{"type":"parameters_stop_4","id":"|QT$BAq|OFa6@C.FxWR;","fields":{"VALUE":"Stop.HOLD"}}}},"next":{"block":{"type":"blockWaitTime","id":"Kbt6XoM`XL)}G1~-+qdE","inputs":{"VALUE0":{"shadow":{"type":"unit_time","id":"*+Hup}?=R}QRHr15D:^U","fields":{"VALUE0":1000}}}}}}}}}}}}}]},"variables":[{"name":"red","id":"d56YNK9:TGiQE`!l/apb","type":"ColorDef"},{"name":"orange","id":"H/)^bugR{zE[n5TM6O$[","type":"ColorDef"},{"name":"yellow","id":"Vvvj~9090#@-0,s6?D],","type":"ColorDef"},{"name":"green","id":"WDdCVlIDE`:W#g@q[j:r","type":"ColorDef"},{"name":"cyan","id":"ErJE*!x.Flw4P0LSyF%c","type":"ColorDef"},{"name":"blue","id":"Y~tBL+|8%+3b)pP+o%9s","type":"ColorDef"},{"name":"violet","id":"XvAa^*Vm(#pvLyDz@.:A","type":"ColorDef"},{"name":"magenta","id":"U|O7S=_kmm]esW^_p+n]","type":"ColorDef"},{"name":"white","id":"j3nJiOMj[yaijFH-]:V4","type":"ColorDef"},{"name":"none","id":"xY0?}z|Ns.SLwPioCgQ=","type":"ColorDef"},{"name":"motor","id":"oa=6ALE#Lhs`C.PoT*$y","type":"Motor"}],"info":{"type":"pybricks","version":"1.2.3"}}
from pybricks.parameters import Direction, Port, Stop
from pybricks.pupdevices import Motor
from pybricks.tools import wait

# Set up all devices.
motor = Motor(Port.A, Direction.CLOCKWISE)


# The main program starts here.
motor.run_angle(500, 360)
wait(1000)
motor.run_angle(500, -360)
wait(1000)
