# pybricks blocks file:{"blocks":{"languageVersion":0,"blocks":[{"type":"blockGlobalSetup","id":"bjK,wS1MYO7aiYkFSwd{","x":20,"y":18,"deletable":false,"next":{"block":{"type":"variables_set_ultrasonic_sensor","id":"dZ1_$tvX@SsrW}R.iZ*}","fields":{"VAR":{"id":"MM!vVG#sqK)o.@R8x=M$"}},"inputs":{"PORT":{"shadow":{"type":"blockParametersPort","id":"8H?xxb)v`@hs~ttLto:U","fields":{"NAME":"D"}}}},"next":{"block":{"type":"variables_set_stopwatch","id":"!0ZteB%a0xmj56%7K)@t","fields":{"VAR":{"id":"f!)#u^psK(+1@vc4V)+g"}}}}}}},{"type":"blockGlobalStart","id":"3tJe|AWl0baN(wH9a$@.","x":20,"y":190,"deletable":false,"next":{"block":{"type":"blockPrint","id":"u/?*5|9C!,G;.P?Oq[CA","extraState":{"optionLevel":1},"fields":{"SEP":"SEP_COMMA_ONLY"},"inputs":{"TEXT0":{"shadow":{"type":"text","id":"gM6k~p7}Yr4DU$|y!.QN","fields":{"TEXT":"Time"}}},"TEXT1":{"shadow":{"type":"text","id":":N)!bK[HvzRSM8uyDotg","fields":{"TEXT":"Distance"}}}},"next":{"block":{"type":"blockFlowRepeat","id":"/[Vf^8xj}HOsR~|ElM`:","inputs":{"TIMES":{"shadow":{"type":"blockMathNumber","id":"e!T5PL[g97!dCLA@{=C+","fields":{"NUM":50}}},"DO":{"block":{"type":"blockPrint","id":"j,,T}?rBkaW$1v?olp4p","extraState":{"optionLevel":1},"fields":{"SEP":"SEP_COMMA_ONLY"},"inputs":{"TEXT0":{"shadow":{"type":"text","id":"!x5.0YiWya^`(y)yO5B8","fields":{"TEXT":"Distance:"}},"block":{"type":"blockStopWatchTime","id":"JWy.0Z.K#WntRhfDnL{v","inputs":{"VAR":{"shadow":{"type":"variables_get_stopwatch","id":"2d#!We:plRjJK5J;*iQ]","fields":{"VAR":{"id":"f!)#u^psK(+1@vc4V)+g","name":"watch","type":"StopWatch"}}}}}}},"TEXT1":{"shadow":{"type":"text","id":"]B8$rg}_3L2DH4^Lp$hb","fields":{"TEXT":"abc"}},"block":{"type":"blockDistance","id":"@Zh(;(d%#6|9=z^SK0i.","inputs":{"VAR":{"shadow":{"type":"variables_get_distance_device","id":"0u`-2RT#t~8,?QtRB:78","fields":{"VAR":{"id":"MM!vVG#sqK)o.@R8x=M$","name":"sensor","type":"UltrasonicSensor"}}}}}}}},"next":{"block":{"type":"blockWaitTime","id":"BO;**8Wh]oy$l1K!(98/","inputs":{"VALUE0":{"shadow":{"type":"unit_time","id":"@f|$O=ho8;e(epuag}/N","fields":{"VALUE0":100}}}}}}}}}}}}}}]},"variables":[{"name":"red","id":"_f*1dAFi;USV0Q@}qS2%","type":"ColorDef"},{"name":"orange","id":"ZuVMZe7f{vJ).].8jAoq","type":"ColorDef"},{"name":"yellow","id":"C((nk*Sg,nCM~Nr#HUTU","type":"ColorDef"},{"name":"green","id":",82n|AV_oN^zjCKT{2ve","type":"ColorDef"},{"name":"cyan","id":"t9sT{/ez~X7Zd^9GKkB/","type":"ColorDef"},{"name":"blue","id":"f=1~g-$eP);frKrgyRZe","type":"ColorDef"},{"name":"violet","id":"J^/y7N#+PF?HF~JMYbu+","type":"ColorDef"},{"name":"magenta","id":"8*cL$z-6DI)2hY4nKrws","type":"ColorDef"},{"name":"white","id":"DgN)MSTUtnmJdUCw5Mz[","type":"ColorDef"},{"name":"none","id":"5_J7}]jZRj?~htfct6tX","type":"ColorDef"},{"name":"sensor","id":"MM!vVG#sqK)o.@R8x=M$","type":"UltrasonicSensor"},{"name":"watch","id":"f!)#u^psK(+1@vc4V)+g","type":"StopWatch"}],"info":{"type":"pybricks","version":"1.3.2"}}
from pybricks.parameters import Port
from pybricks.pupdevices import UltrasonicSensor
from pybricks.tools import StopWatch, wait

# Set up all devices.
sensor = UltrasonicSensor(Port.D)
watch = StopWatch()


# The main program starts here.
print('Time', 'Distance', sep=",")
for count in range(50):
    print(watch.time(), sensor.distance(), sep=",")
    wait(100)
