# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pybricks
email: team@pybricks.com
description: >- # Ignore new lines
  Pybricks lets you code your LEGO® creations to make them come alive. Learn to
  build and code your own creations, or follow along with our tutorials.
  Pybricks works with LEGO MINDSTORMS, SPIKE Prime, LEGO Technic, LEGO City
  Trains, LEGO Boost, and more.
github_username: pybricks
minimal_mistakes_skin: default
search: true
logo: /misc/images/pybricks-logo.png

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: "blog/page:num"
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*README*"
  - "*.code-workspace"
  - projects/AUTHORS.md
  - projects/CONTRIBUTING.md
  - projects/LICENSE
  - projects/setup.cfg

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  name   : "Laurens Valk"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I make things."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Mastodon"
      icon: "fas fa-fw fa-rss-square"
      url: "https://fosstodon.org/@laurensvalk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pybricks"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/pybricks"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/Pybricks/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pybricks"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/pybricks"

after_footer_scripts:
  - assets/js/copy-code.js
  - assets/js/lite-yt-embed.js

defaults:
  # _posts, indexed automatically based on filename, linked via tags, categories.
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
  # Install pages, indexing based on directory structure
  - scope:
      path: "install"
      type: pages
    values:
      layout: single
      author_profile: false
      share: true
      toc: true
      toc_sticky: true
      sidebar:
        nav: "install"
  # About pages, indexing based on directory structure
  - scope:
      path: "about"
      type: pages
    values:
      layout: single
      author_profile: false
      share: true
      toc: true
      toc_sticky: true
      sidebar:
        nav: "about"
  # Other pages, indexing based on unique permalink for each page.
  - scope:
      path: "misc"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      toc: false
      toc_sticky: true
  - scope: # Revisit: drop legacy projects
      path: "projects"
      type: pages
    values:
      layout: project
      author_profile: false
      toc: false



category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
